version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: prompt_museum_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prompt_museum
      MYSQL_USER: prompt_user
      MYSQL_PASSWORD: prompt_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prompt_museum_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: prompt_user
      PMA_PASSWORD: prompt_password
    depends_on:
      - mysql

volumes:
  mysql_data: