[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]
workDir = "/app"

[phases.install]
cmd = "cp backend/package.json backend/yarn.lock ./ && yarn install --frozen-lockfile"

[phases.build]
cmd = "cp -r backend/* ./ && yarn build"

[start]
cmd = "yarn start:prod"